title: "Lab3"
output: html_notebook
---

```{r}
install.packages("ggplot2")
library(ggplot2)
install.packages("dplyr")
library(dplyr)
```

install packages

```{r}
install.packages("imager")
library(imager)
```
Cont.

```{r}
im <- load.image("D://Users//drewk1992//Documents//UGA//Thesis//Pictures//lab3Test.png")
bdf <- as.data.frame(im)
head(bdf,3)
plot(im)
```
Get info on image
```{r}
dim(im)
```
create a histogram for each color channels rgb value frequency

```{r}
R(im) %>% hist(main="Red channel values in mine picture");G(im) %>% hist(main="Red channel values in mine picture");B(im) %>% hist(main="Red channel values in mine picture")
```
Create a data frame to store pic in and create header for df and plot it
```{r}
picdataframe <- as.data.frame(im)
head(picdataframe,3)
```
 use picture data frame with gg plot to create 3 histograms for each channels pixel freq
```{r}
picdataframe <- plyr::mutate(picdataframe,channel=factor(cc,labels=c('R','G','B')))
ggplot(picdataframe,aes(value,col=channel))+geom_histogram(bins=30)+facet_wrap(~ channel)
```
Plot equlaized image
```{r}
hist.eq <- function(im) as.cimg(ecdf(im)(im),dim=dim(im))
split <- imsplit(im,"c")
split
split.eq <- llply(split,hist.eq)
imappend(split.eq,"c") %>% plot(main="3 channel Hist Equalization")
```

Perform Image Gradient Magnitude analysis
…
```{r}
im.g <- grayscale(im)
imgradient(im.g,"xy") %>% enorm %>% plot(main="Gradient magnitude")
```
```{r}
imhessian(im.g)
```
```{r}
Hdet <- with(imhessian(im),(xx*yy - xy^2))
plot(Hdet,main="Determinant of Hessian")
```
```{r}
threshold(Hdet,"99%") %>% plot(main="Determinant: 1% highest values")
```

```{r}
lab <- threshold(Hdet,"99%") %>% label
plot(lab,main="Labelled regions")
```
```{r}
df <- as.data.frame(lab) %>% subset(value>0)
head(df,3)
```

 
 
```{r}
centers <- ddply(df,.(value),summarise,mx=mean(x),my=mean(y))
```
```{r}
plot(im)
with(centers,points(mx,my,col="red"))
```

```{r}
hessdet <- function(im,scale=1) isoblur(im,scale) %>% imhessian %$% { scale^2*(xx*yy - xy^2) }
dat <- ldply(c(2,3,4),function(scale) hessdet(im,scale) %>% as.data.frame %>% mutate(scale=scale))
p <- ggplot(dat,aes(x,y))+geom_raster(aes(fill=value))+facet_wrap(~ scale)
p+scale_x_continuous(expand=c(0,0))+scale_y_continuous(expand=c(0,0),trans=scales::reverse_trans())
```
```{r}
scales <- seq(2,20,l=10)

d.max <- llply(scales,function(scale) hessdet(im,scale)) %>% parmax
plot(d.max,main="Point-wise maximum across scales")
```

```{r}
i.max <- llply(scales,function(scale) hessdet(im,scale)) %>% which.parmax
plot(i.max,main="Index of the point-wise maximum \n across scales")
```
```{r}

labs <- d.max %>% threshold("96%") %>% label %>% as.data.frame
#Add scale indices
labs <- mutate(labs,index=as.data.frame(i.max)$value)
regs <- dplyr::group_by(labs,value) %>% dplyr::summarise(mx=mean(x),my=mean(y),scale.index=mean(index))
p <- ggplot(as.data.frame(im),aes(x,y))+geom_raster(aes(fill=value))+geom_point(data=regs,aes(mx,my,size=scale.index),pch=2,col="red")
p+scale_fill_gradient(low="black",high="white")+scale_x_continuous(expand=c(0,0))+scale_y_continuous(expand=c(0,0),trans=scales::reverse_trans())
```

